version: '3'
services:
  animebyter:
    build: .
    container_name: animebyter
    environment:
        - qbit_url=http://qbittorrent:8080
        - qbit_user=admin
        - qbit_pass=adminadmin
        - ab_key=YOUR_ANIMEBYTES_KEY
        - discord_token=YOUR_DISCORD_TOKEN
        - download_path=/Anime
    volumes:
        - ./db:/db
    networks:
        - qbit-network
    restart: unless-stopped

networks:
  qbit-network:
    external:
      name: qbittorrent_qbit-network